sudo: false

language: python
python:
  - 3.4
  - 3.5

cache:
  directories:
    - $HOME/.cache/pip


# blacklist
branches:
  except:
    - topic/rewrite_phantomjs
    - topic/rewrite_phantomjs_2


# command to install dependencies
install:
  - travis_retry pip install -q -r requirements.txt;
  - travis_retry pip install -q coverage python-coveralls warcat youtube-dl


# command to run tests
script:
  - pip install . -t thematrix/ --no-dependencies
  - cd thematrix/ && nosetests --with-coverage --cover-package=wpull --cover-branches


after_success:
  - coveralls
